#pragma once

#include <string>
#include <unordered_map>

#include <fmt/format.h>

namespace map
{

namespace doom
{

inline std::string getThingClassName(int type)
{
	static const std::unordered_map<int, std::string> _names = {
	{ 1, "doom_player_1_start" },
	{ 2, "doom_player_2_start" },
	{ 3, "doom_player_3_start" },
	{ 4, "doom_player_4_start" },
	{ 5, "doom_blue_keycard" },
	{ 6, "doom_yellow_keycard" },
	{ 7, "doom_spider_mastermind" },
	{ 8, "doom_backpack" },
	{ 9, "doom_former_human_sergeant" },
	{ 10, "doom_guts_and_bones" },
	{ 11, "doom_deathmatch_start" },
	{ 12, "doom_guts_and_bones_2" },
	{ 13, "doom_red_keycard" },
	{ 14, "doom_teleport_destination" },
	{ 15, "doom_dead_player" },
	{ 16, "doom_cyberdemon" },
	{ 17, "doom_energy_pack" },
	{ 18, "doom_dead_former_human" },
	{ 19, "doom_dead_former_human_sargeant" },
	{ 20, "doom_dead_imp" },
	{ 21, "doom_dead_demon" },
	{ 22, "doom_dead_cacodemon" },
	{ 23, "doom_dead_lost_soul" },
	{ 24, "doom_pool_of_blood" },
	{ 25, "doom_impaled_body" },
	{ 26, "doom_impaled_body_twitching" },
	{ 27, "doom_skull_on_pole" },
	{ 28, "doom_heads_on_pole" },
	{ 29, "doom_pile_of_skulls" },
	{ 30, "doom_tall_green_pillar" },
	{ 31, "doom_short_green_pillar" },
	{ 32, "doom_tall_red_pillar" },
	{ 33, "doom_short_red_pillar" },
	{ 34, "doom_candle" },
	{ 35, "doom_candelabra" },
	{ 36, "doom_pillar_pumping_heart" },
	{ 37, "doom_red_pillar_skull" },
	{ 38, "doom_red_skull_key" },
	{ 39, "doom_yellow_skull_key" },
	{ 40, "doom_blue_skull_key" },
	{ 41, "doom_evil_eye" },
	{ 42, "doom_flaming_skulls" },
	{ 43, "doom_short_grey_tree" },
	{ 44, "doom_tall_blue_torch" },
	{ 45, "doom_tall_green_torch" },
	{ 46, "doom_tall_red_torch" },
	{ 47, "doom_tree_stump" },
	{ 48, "doom_tech_column" },
	{ 49, "doom_hanging_swaying_body_blocking" },
	{ 50, "doom_hanging_body_arms_out_blocking" },
	{ 51, "doom_hanging_one_legged_body_blocking" },
	{ 52, "doom_hanging_legs_blocking" },
	{ 53, "doom_hanging_leg_blocking" },
	{ 54, "doom_large_brown_tree" },
	{ 55, "doom_short_blue_torch" },
	{ 56, "doom_short_green_torch" },
	{ 57, "doom_short_red_torch" },
	{ 58, "doom_spectre" },
	{ 59, "doom_hanging_body_arms_out" },
	{ 60, "doom_hanging_legs" },
	{ 61, "doom_hanging_one_legged_body" },
	{ 62, "doom_hanging_leg" },
	{ 63, "doom_hanging_swaying_body" },
	{ 64, "doom_arch_vile" },
	{ 65, "doom_chaingunner" },
	{ 66, "doom_revenant" },
	{ 67, "doom_mancubus" },
	{ 68, "doom_arachnotron" },
	{ 69, "doom_hell_knight" },
	{ 70, "doom_burning_barrel" },
	{ 71, "doom_pain_elemental" },
	{ 72, "doom_hanging_keen" },
	{ 73, "doom_hanging_body_guts_removed" },
	{ 74, "doom_hanging_body_guts_brain_removed" },
	{ 75, "doom_hanging_torso_looking_down" },
	{ 76, "doom_hanging_torso_open_skull" },
	{ 77, "doom_hanging_torso_looking_up" },
	{ 78, "doom_hanging_torso_brain_removed" },
	{ 79, "doom_pool_of_blood_2" },
	{ 80, "doom_pool_of_blood_3" },
	{ 81, "doom_pool_of_brains" },
	{ 82, "doom_super_shotgun" },
	{ 83, "doom_megasphere" },
	{ 84, "doom_wolfenstein_3d_ss" },
	{ 85, "doom_tall_techno_lamp" },
	{ 86, "doom_short_techno_lamp" },
	{ 87, "doom_boss_spawn_spot" },
	{ 88, "doom_boss_brain" },
	{ 89, "doom_boss_shooter" },
	{ 2001, "doom_shotgun" },
	{ 2002, "doom_chaingun" },
	{ 2003, "doom_rocket_launcher" },
	{ 2004, "doom_plasma_gun" },
	{ 2005, "doom_chainsaw" },
	{ 2006, "doom_bfg9000" },
	{ 2007, "doom_ammo_clip" },
	{ 2008, "doom_shotgun_shells" },
	{ 2010, "doom_rocket" },
	{ 2011, "doom_stimpack" },
	{ 2012, "doom_medikit" },
	{ 2013, "doom_soul_sphere" },
	{ 2014, "doom_health_potion" },
	{ 2015, "doom_armour_helmet" },
	{ 2018, "doom_green_armour" },
	{ 2019, "doom_blue_armour" },
	{ 2022, "doom_invulnerability_sphere" },
	{ 2023, "doom_berserk_pack" },
	{ 2024, "doom_partial_invisibility_sphere" },
	{ 2025, "doom_radiation_shielding_suit" },
	{ 2026, "doom_computer_area_map" },
	{ 2028, "doom_yellow_lamp" },
	{ 2035, "doom_barrel" },
	{ 2045, "doom_lite_amp_goggles" },
	{ 2046, "doom_box_of_rockets" },
	{ 2047, "doom_energy_cell" },
	{ 2048, "doom_box_of_ammo" },
	{ 2049, "doom_box_of_shells" },
	{ 3001, "doom_imp" },
	{ 3002, "doom_demon" },
	{ 3003, "doom_baron_of_hell" },
	{ 3004, "doom_former_human" },
	{ 3005, "doom_cacodemon" },
	{ 3006, "doom_lost_soul" },
	{ 32000, "doom_doom_builder_camera" },
	};

	auto found = _names.find(type);

	return found != _names.end() ? found->second : fmt::format("doom_thing_{0:d}", type);
}

}

}
